Added prop to allow squatchReferralCookie to return _saasquatch cooki…
saasquatch/squatch-js pull request #54
Opened 2023-03-06 23:17 UTC by 00salmon

…e as is

## Description of the change

> Description here

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation or Development tools (readme, specs, tests, code formatting)

## Links

- Jira issue number: (PUT IT HERE)
- Process.st launch checklist: (PUT IT HERE)

## Checklists

### Development

- [ ] [Prettier](https://www.npmjs.com/package/prettier) was run (if applicable)
- [ ] The behaviour changes in the pull request are covered by specs
- [ ] All tests related to the changed code pass in development

### Paperwork

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has a Jira number
- [ ] This pull request has a Process.st launch checklist

### Code review

- [ ] Changes have been reviewed by at least one other engineer
- [ ] Security impacts of this change have been considered

2023-03-15 17:36 UTC, johanventer requested changes

2023-03-15 17:36 UTC, johanventer commented on src/api/WidgetApi.ts
>  }
Why don't you type this properly instead of returning `Promise<Object>` ?

2023-03-15 17:36 UTC, johanventer commented on src/types.ts
> +};
This documentation is kinda bad, as this does not `Looks up the referral code of the current user` as it's just a type

2023-03-15 17:36 UTC, johanventer commented on CHANGELOG.md
> +  .squatchReferralCookie(true)
This is wrong based on looking at the code where it looks like `squatchReferralCookie` takes an options object, and not a boolean.

2023-03-15 17:36 UTC, johanventer commented on CHANGELOG.md
> +  });
Also this won't actually work if you are returning the `_saasquatch` string will it? Looks like the function will return an object `{ _saasquatch: "..." }` in this case.

2023-03-15 17:45 UTC, 00salmon commented on src/api/WidgetApi.ts
>  }
Derek discussed with Logan and we are going to updating this to return an object with the codes and the encoded cookie as one and no parameters needed

2023-03-15 17:46 UTC, 00salmon commented on CHANGELOG.md
> +  .squatchReferralCookie(true)
example wasn't updated after the last edition 👍 i'll add this as a coda task so we don't forget

2023-04-03 21:10 UTC, johanventer reviewed
Looks good, needs PR hygeine

2023-04-05 16:08 UTC, DerekSiemens commented on CHANGELOG.md
> +## [2.4.2] - 2023-04-03
Flagging to update date here before launch

2023-04-05 17:01 UTC, 00salmon commented on CHANGELOG.md
> +## [2.4.2] - 2023-04-03
```suggestion
## [2.4.2] - 2023-04-05
```

2023-04-06 00:08 UTC, 00salmon commented on CHANGELOG.md
> +## [2.4.2] - 2023-04-05
```suggestion
## [2.4.2] - 2023-04-10
```

2023-04-10 16:56 UTC, johanventer approved these changes

2023-04-10 17:27 UTC, merged